### ISSUE TITLE
STATUS_MASK constants from OpenDDS

### ISSUE THREAD

**Issue by adamsj-ros** [oci-labs/rmw_opendds#12]
See https://github.com/objectcomputing/OpenDDS/issues/1306, this mask is not yet there in OpenDDS

_Originally posted by @jwillemsen in https://github.com/oci-labs/rmw_opendds/pull/11_

**Comment by mitza-oci** [comment]
You can use `0` for a "none" constant the works everywhere.

**Comment by mitza-oci** [comment]
Looks like this was already fixed in #22
