### ISSUE TITLE
Make use of OpenDDS cmake support

### ISSUE THREAD

**Issue by jwillemsen** [oci-labs/rmw_opendds#3]
After OpenDDS 3.13 cmake support got added, we should make use of that in this module

**Comment by adamsj-ros** [comment]
I think this is complete based on my work with https://github.com/jwillemsen/rmw_opendds on branch jwi-openddsros2 and OpenDDS master branch. We can check after the current PR and transfer are complete.

**Comment by mitza-oci** [comment]
Fixed by #17
